name: "Build iOS app"

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: self-hosted
    steps:
      - name: Verificando a versão do Xcode 
        run: /usr/bin/xcodebuild -version

      - name: Fazendo o checkout do repositório
        uses: actions/checkout@v4

      - name: Gerando a build
        run: |
          xcodebuild -scheme "I am Groot" \
          -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive
